# TCL File Generated by Component Editor 18.1
# Wed Jan 04 21:06:56 CET 2023
# DO NOT MODIFY


# 
# IP_CAM_Top "IP_CAM_Top" v1.0
#  2023.01.04.21:06:56
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module IP_CAM_Top
# 
set_module_property DESCRIPTION ""
set_module_property NAME IP_CAM_Top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME IP_CAM_Top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL IP_CAM_Top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file IP_CAM_Top.vhd VHDL PATH ip/ip_cam/IP_CAM_Top.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock Clk clk Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset Reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave AS_Address address Input 3
add_interface_port avalon_slave AS_Read_n read_n Input 1
add_interface_port avalon_slave AS_Write_n write_n Input 1
add_interface_port avalon_slave AS_Datard readdata Output 32
add_interface_port avalon_slave AS_Datawr writedata Input 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset Reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master AM_Address address Output 32
add_interface_port avalon_master AM_BurstCount burstcount Output 2
add_interface_port avalon_master AM_Datawr writedata Output 32
add_interface_port avalon_master AM_WaitRequest waitrequest Input 1
add_interface_port avalon_master AM_Write_n write_n Output 1
add_interface_port avalon_master AM_byteEnable_n byteenable_n Output 4


# 
# connection point Reset
# 
add_interface Reset reset end
set_interface_property Reset associatedClock clock
set_interface_property Reset synchronousEdges DEASSERT
set_interface_property Reset ENABLED true
set_interface_property Reset EXPORT_OF ""
set_interface_property Reset PORT_NAME_MAP ""
set_interface_property Reset CMSIS_SVD_VARIABLES ""
set_interface_property Reset SVD_ADDRESS_GROUP ""

add_interface_port Reset nReset reset_n Input 1


# 
# connection point cam_reset
# 
add_interface cam_reset conduit end
set_interface_property cam_reset associatedClock clock
set_interface_property cam_reset associatedReset Reset
set_interface_property cam_reset ENABLED true
set_interface_property cam_reset EXPORT_OF ""
set_interface_property cam_reset PORT_NAME_MAP ""
set_interface_property cam_reset CMSIS_SVD_VARIABLES ""
set_interface_property cam_reset SVD_ADDRESS_GROUP ""

add_interface_port cam_reset CamReset_n output Output 1


# 
# connection point cam_hsync
# 
add_interface cam_hsync conduit end
set_interface_property cam_hsync associatedClock clock
set_interface_property cam_hsync associatedReset ""
set_interface_property cam_hsync ENABLED true
set_interface_property cam_hsync EXPORT_OF ""
set_interface_property cam_hsync PORT_NAME_MAP ""
set_interface_property cam_hsync CMSIS_SVD_VARIABLES ""
set_interface_property cam_hsync SVD_ADDRESS_GROUP ""

add_interface_port cam_hsync Cam_Hsync input Input 1


# 
# connection point cam_mclk
# 
add_interface cam_mclk conduit end
set_interface_property cam_mclk associatedClock clock
set_interface_property cam_mclk associatedReset ""
set_interface_property cam_mclk ENABLED true
set_interface_property cam_mclk EXPORT_OF ""
set_interface_property cam_mclk PORT_NAME_MAP ""
set_interface_property cam_mclk CMSIS_SVD_VARIABLES ""
set_interface_property cam_mclk SVD_ADDRESS_GROUP ""

add_interface_port cam_mclk Cam_Mclk output Output 1


# 
# connection point cam_pxlclk
# 
add_interface cam_pxlclk conduit end
set_interface_property cam_pxlclk associatedClock clock
set_interface_property cam_pxlclk associatedReset ""
set_interface_property cam_pxlclk ENABLED true
set_interface_property cam_pxlclk EXPORT_OF ""
set_interface_property cam_pxlclk PORT_NAME_MAP ""
set_interface_property cam_pxlclk CMSIS_SVD_VARIABLES ""
set_interface_property cam_pxlclk SVD_ADDRESS_GROUP ""

add_interface_port cam_pxlclk Cam_Pixclk input Input 1


# 
# connection point cam_vsync
# 
add_interface cam_vsync conduit end
set_interface_property cam_vsync associatedClock clock
set_interface_property cam_vsync associatedReset ""
set_interface_property cam_vsync ENABLED true
set_interface_property cam_vsync EXPORT_OF ""
set_interface_property cam_vsync PORT_NAME_MAP ""
set_interface_property cam_vsync CMSIS_SVD_VARIABLES ""
set_interface_property cam_vsync SVD_ADDRESS_GROUP ""

add_interface_port cam_vsync Cam_Vsync input Input 1


# 
# connection point cam_data
# 
add_interface cam_data conduit end
set_interface_property cam_data associatedClock clock
set_interface_property cam_data associatedReset ""
set_interface_property cam_data ENABLED true
set_interface_property cam_data EXPORT_OF ""
set_interface_property cam_data PORT_NAME_MAP ""
set_interface_property cam_data CMSIS_SVD_VARIABLES ""
set_interface_property cam_data SVD_ADDRESS_GROUP ""

add_interface_port cam_data Cam_data input Input 6

