# TCL File Generated by Component Editor 18.1
# Wed Jan 04 20:46:48 CET 2023
# DO NOT MODIFY


# 
# IP_LCD "IP_LCD" v3.0
#  2023.01.04.20:46:48
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module IP_LCD
# 
set_module_property DESCRIPTION ""
set_module_property NAME IP_LCD
set_module_property VERSION 3.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME IP_LCD
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL IP_LCD_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file IP_LCD_wrapper.vhd VHDL PATH ip/IP_LCD/IP_LCD_wrapper.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 addressSlave address Input 3
add_interface_port avalon_slave_0 readSlave read Input 1
add_interface_port avalon_slave_0 readdataSlave readdata Output 32
add_interface_port avalon_slave_0 writeSlave write Input 1
add_interface_port avalon_slave_0 writedataSlave writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink nReset reset_n Input 1


# 
# connection point avalon_master_1
# 
add_interface avalon_master_1 avalon start
set_interface_property avalon_master_1 addressUnits SYMBOLS
set_interface_property avalon_master_1 associatedClock clock
set_interface_property avalon_master_1 associatedReset reset_sink
set_interface_property avalon_master_1 bitsPerSymbol 8
set_interface_property avalon_master_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_master_1 burstcountUnits WORDS
set_interface_property avalon_master_1 doStreamReads false
set_interface_property avalon_master_1 doStreamWrites false
set_interface_property avalon_master_1 holdTime 0
set_interface_property avalon_master_1 linewrapBursts false
set_interface_property avalon_master_1 maximumPendingReadTransactions 0
set_interface_property avalon_master_1 maximumPendingWriteTransactions 0
set_interface_property avalon_master_1 readLatency 0
set_interface_property avalon_master_1 readWaitTime 1
set_interface_property avalon_master_1 setupTime 0
set_interface_property avalon_master_1 timingUnits Cycles
set_interface_property avalon_master_1 writeWaitTime 0
set_interface_property avalon_master_1 ENABLED true
set_interface_property avalon_master_1 EXPORT_OF ""
set_interface_property avalon_master_1 PORT_NAME_MAP ""
set_interface_property avalon_master_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_1 addressMaster address Output 32
add_interface_port avalon_master_1 burstcount burstcount Output 4
add_interface_port avalon_master_1 readMaster read Output 1
add_interface_port avalon_master_1 readdataMaster readdata Input 32
add_interface_port avalon_master_1 readdatavalidMaster readdatavalid Input 1
add_interface_port avalon_master_1 waitrequestMaster waitrequest Input 1
add_interface_port avalon_master_1 writeMaster write Output 1
add_interface_port avalon_master_1 writedataMaster writedata Output 32


# 
# connection point conduit_CSX
# 
add_interface conduit_CSX conduit end
set_interface_property conduit_CSX associatedClock clock
set_interface_property conduit_CSX associatedReset reset_sink
set_interface_property conduit_CSX ENABLED true
set_interface_property conduit_CSX EXPORT_OF ""
set_interface_property conduit_CSX PORT_NAME_MAP ""
set_interface_property conduit_CSX CMSIS_SVD_VARIABLES ""
set_interface_property conduit_CSX SVD_ADDRESS_GROUP ""

add_interface_port conduit_CSX CSX export Output 1


# 
# connection point conduit_D
# 
add_interface conduit_D conduit end
set_interface_property conduit_D associatedClock clock
set_interface_property conduit_D associatedReset reset_sink
set_interface_property conduit_D ENABLED true
set_interface_property conduit_D EXPORT_OF ""
set_interface_property conduit_D PORT_NAME_MAP ""
set_interface_property conduit_D CMSIS_SVD_VARIABLES ""
set_interface_property conduit_D SVD_ADDRESS_GROUP ""

add_interface_port conduit_D D export Output 16


# 
# connection point conduit_DCX
# 
add_interface conduit_DCX conduit end
set_interface_property conduit_DCX associatedClock clock
set_interface_property conduit_DCX associatedReset reset_sink
set_interface_property conduit_DCX ENABLED true
set_interface_property conduit_DCX EXPORT_OF ""
set_interface_property conduit_DCX PORT_NAME_MAP ""
set_interface_property conduit_DCX CMSIS_SVD_VARIABLES ""
set_interface_property conduit_DCX SVD_ADDRESS_GROUP ""

add_interface_port conduit_DCX D_CX export Output 1


# 
# connection point conduit_RDX
# 
add_interface conduit_RDX conduit end
set_interface_property conduit_RDX associatedClock clock
set_interface_property conduit_RDX associatedReset reset_sink
set_interface_property conduit_RDX ENABLED true
set_interface_property conduit_RDX EXPORT_OF ""
set_interface_property conduit_RDX PORT_NAME_MAP ""
set_interface_property conduit_RDX CMSIS_SVD_VARIABLES ""
set_interface_property conduit_RDX SVD_ADDRESS_GROUP ""

add_interface_port conduit_RDX RDX export Output 1


# 
# connection point conduit_WRX
# 
add_interface conduit_WRX conduit end
set_interface_property conduit_WRX associatedClock clock
set_interface_property conduit_WRX associatedReset reset_sink
set_interface_property conduit_WRX ENABLED true
set_interface_property conduit_WRX EXPORT_OF ""
set_interface_property conduit_WRX PORT_NAME_MAP ""
set_interface_property conduit_WRX CMSIS_SVD_VARIABLES ""
set_interface_property conduit_WRX SVD_ADDRESS_GROUP ""

add_interface_port conduit_WRX WRX export Output 1


# 
# connection point conduit_LCDON
# 
add_interface conduit_LCDON conduit end
set_interface_property conduit_LCDON associatedClock clock
set_interface_property conduit_LCDON associatedReset reset_sink
set_interface_property conduit_LCDON ENABLED true
set_interface_property conduit_LCDON EXPORT_OF ""
set_interface_property conduit_LCDON PORT_NAME_MAP ""
set_interface_property conduit_LCDON CMSIS_SVD_VARIABLES ""
set_interface_property conduit_LCDON SVD_ADDRESS_GROUP ""

add_interface_port conduit_LCDON LCD_ON export Output 1


# 
# connection point conduit_LCDRESET
# 
add_interface conduit_LCDRESET conduit end
set_interface_property conduit_LCDRESET associatedClock clock
set_interface_property conduit_LCDRESET associatedReset reset_sink
set_interface_property conduit_LCDRESET ENABLED true
set_interface_property conduit_LCDRESET EXPORT_OF ""
set_interface_property conduit_LCDRESET PORT_NAME_MAP ""
set_interface_property conduit_LCDRESET CMSIS_SVD_VARIABLES ""
set_interface_property conduit_LCDRESET SVD_ADDRESS_GROUP ""

add_interface_port conduit_LCDRESET LCD_RESET export Output 1

